db_path: './data/softpower.db'
db_schema: './sql/schema.sql'
gai_data: './gai_summary/data'
gai_json: './gai_summary/json'
dsr_data: 'backend/dsr'
start_date: '2024-08-01'
sql: './sql'
report_directory: './'
aws:
  secret_name: "AZURE_OPENAI_API_KEY_NORTHCENTRALUS"
  region_name: "us-east-1"
  api_version: "2024-08-01-preview"
  4_1_model: gpt-4.1 
  4_1_version: '2025-04-14'
  default_model: "gpt-4o-mini"
text_field: 'BODY'
identifier: 'ATOM ID'
gai_output: 'GAI Output'
chunk_dedup: 'ATOM ID'
chunk_size: 1000
max_records: 300
summary_sample_percentage: .5
sample_data: True
sample_size: 10
delete_after_processing: False
create_sample: False
atom_collection: 'ne_auto'
report_months:
  - '2024-07'
  - '2024-08'
  - '2024-09'
  - '2024-10'
  - '2024-11'
  - '2024-12'
  - '2025-01'
  - '2025-02'
event_models:
  - 'all-MiniLM-L6-v2'
  - 'paraphrase-mpnet-base-v2'
  - 'paraphrase-distilroberta-base-v1'
  - 'paraphrase-MiniLM-L6-v2'
    
projects:
  model: 'all-MiniLM-L6-v2'
  batch_size: 1000
  eps: 0.4
  min_samples: 2
  metric: 'cosine'
  
cluster:
  threshold: 50
  event_threshold: 50
  max_passes: 5
  metric: 'cosine'
  eps: 0.55
  eps_decay: 0.1
  min_samples: 2
  refine_clusters: True
  text_columns:
    - event-name
    - distilled-text
    - salience-justification

fields:
    raw_atom:
      - Title
      - BODY
      - Source Name
      - 'Source Date, Start'
      - Collection Name
      - ATOM ID
    extract:
      - salience-justification
      - salience-bool
      - category
      - category-justification
      - subcategory 
      - initiating-country
      - recipient-country
      - project-name
      - LAT_LONG
      - location
      - monetary-commitment
      - distilled-text
      - event-name
    dsr:
      - ATOM ID
      - title 
      - source-name
      - source-geofocus
    gai_salience:
      - ATOM ID
      - Salience
      - Title
      - BODY
      - Source Name
      - date
      - Collection Name
      - Model
    gai_extraction:
      - ATOM ID
      - salience-bool
      - salience-justification
      - Title
      - BODY
      - Source Name
      - date
      - Collection Name
      - category
      - category-justification
      - subcategory
      - initiating-country
      - recipient-country
      - project-name
      - location
      - lat-long
      - monetary-commitment
      - distilled-text
    gai_result:
      - ATOM ID
      - Title
      - BODY
      - Source Name
      - date
      - Collection Name
      - GAI Output

eval:
    tasks:
      salience: Salience
      category: Category
      subcategory: Subcategory
      init_country: Initiating_Country
      rec_country: Recipient_Country
    meta_fields:
      - 'ATOM ID'
      - 'BODY'
      - 'Distilled_Text'
      
influencers:
  - China
  - Russia
  - Iran
  - Turkey
  - United States

recipients:
  - Bahrain
  - Cyprus
  - Egypt
  - Iran
  - Iraq
  - Israel
  - Jordan
  - Kuwait
  - Lebanon
  - Libya
  - Oman
  - Palestine
  - Qatar
  - Saudi Arabia
  - Syria
  - Turkey
  - United Arab Emirates
  - UAE
  - Yemen

categories:
  - Economic
  - Social
  - Military
  - Diplomacy

subcategories:
  - Trade
  - Infrastructure
  - Food
  - Technology
  - Tourism
  - Industrial
  - Raw Materials
  - Culture
  - Education
  - Healthcare
  - Housing
  - Media
  - Politics
  - Religious
  - "Bilateral/Multilateral Agreements"
  - "Multilateral/Bilateral Commitments"
  - Conflict Resolution
  - Global Governance Participation
  - Sales
  - Joint Exercises
  - Training
  - Conferences
  - Cultural
  - Diaspora Engagement
  - Energy
  - Finance
